### ISSUE TITLE
Wayback robots

### ISSUE THREAD

**Issue by ghost** [Josue87/roboxtractor#1]
Does it pull robots.txt from wayback machine or commoncrawl??

**Comment by Josue87** [comment]
Hi!

I have in mind to add the option to check the robots.txt file from wayback machine, but at the moment it only does a crawl to the web.

**Comment by Josue87** [comment]
I just uploaded a version that checks wayback machine (only the last 5 years). I still have to continue testing. It is used with the -wb flag.
